services:
  drugdb:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ../data/DrugDatabase:/docker-entrypoint-initdb.d
  be: 
    depends_on:
      - drugdb
    restart: on-failure
    env_file:
      - backend.env
    build:
      context: ../drugapi
      dockerfile: ../drugapi/backend.dockerfile
    ports:
      - "8080:8080"

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - be
    command:
      - "http"
      - "http://host.docker.internal:8080"
    environment:
      NGROK_AUTHTOKEN: "2mTfgD91UhsZRtjzHfu4QF8QX1w_2w8JS6svmD1JTb9Nd7gtQ"
    ports:
      - 4040:4040
