spring:
application:
  name: drugapi
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
datasource:
  url: ${SQL_DATABASE}
  username: ${SQL_USERNAME}
  password: ${SQL_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

aws:
  accesskey: ${AWS_ACCESS_KEY}
  secretkey: ${AWS_SECRET_KEY}

google:
  client-id: ${GOOGLE_CLIENT_ID}

salt:
  uuid: ${SALT_UUID}

firebase:
  config:
    path: classpath:firebase-config.json